export const categories = [
  {
    key: "education",
    icon: "🎓",
    title: "Education & Scholarships",
    description: "Student aid, fee reimbursement",
    fields: [
      {
        id: "educationLevel",
        label: "Current education level",
        type: "select",
        key: "educationLevel",
        options: ["Select", "Below 10th", "10th pass", "Intermediate (12th)", "Diploma", "Graduate", "Postgraduate"],
      },
      {
        id: "currentlyStudying",
        label: "Currently studying?",
        type: "toggle",
        key: "currentlyStudying",
        options: ["Yes", "No"],
      },
      {
        id: "courseType",
        label: "Course type",
        type: "select",
        key: "courseType",
        options: ["Select", "General", "Engineering", "Medical", "Law", "Agriculture", "MBA", "MCA", "Other"],
      },
      {
        id: "institutionType",
        label: "Institution type",
        type: "select",
        key: "institutionType",
        options: ["Select", "Government", "Private aided", "Private unaided"],
      },
      {
        id: "fatherOccupation",
        label: "Father's occupation",
        type: "select",
        key: "fatherOccupation",
        options: ["Select", "Government employee", "Private employee", "Farmer", "Daily wage", "Business", "Deceased"],
      },
      {
        id: "annualFees",
        label: "Annual tuition fees (₹)",
        type: "number",
        key: "annualFees",
        placeholder: "e.g. 35000",
      },
    ],
  },
  {
    key: "farmer",
    icon: "🌾",
    title: "Farmer & Agriculture",
    description: "Crop support, land subsidies",
    fields: [
      {
        id: "landAcres",
        label: "Land owned (acres)",
        type: "number",
        key: "landAcres",
        placeholder: "e.g. 2.5",
      },
      {
        id: "farmerType",
        label: "Farmer type",
        type: "select",
        key: "farmerType",
        options: ["Select", "Marginal (less than 1 acre)", "Small (1-2 acres)", "Medium (2-5 acres)", "Large (5+ acres)"],
      },
      {
        id: "cropType",
        label: "Main crop grown",
        type: "select",
        key: "cropType",
        options: ["Select", "Paddy", "Cotton", "Maize", "Groundnut", "Pulses", "Vegetables", "Other"],
      },
      {
        id: "kisanCard",
        label: "Registered under PM-Kisan?",
        type: "toggle",
        key: "kisanCard",
        options: ["Yes", "No"],
      },
      {
        id: "irrigationType",
        label: "Irrigation source",
        type: "select",
        key: "irrigationType",
        options: ["Select", "Rainfed", "Canal", "Borewell", "Tank"],
      },
      {
        id: "cropLoss",
        label: "Faced crop loss recently?",
        type: "toggle",
        key: "cropLoss",
        options: ["Yes", "No"],
      },
    ],
  },
  {
    key: "housing",
    icon: "🏠",
    title: "Housing & Shelter",
    description: "Pucca house, plot allotment",
    fields: [
      {
        id: "houseOwnership",
        label: "Current housing status",
        type: "select",
        key: "houseOwnership",
        options: ["Select", "Own house", "Rented", "Living with relatives", "No house"],
      },
      {
        id: "puccaHouse",
        label: "Has pucca house?",
        type: "toggle",
        key: "puccaHouse",
        options: ["Yes", "No"],
      },
      {
        id: "plotOwnership",
        label: "Owns a plot or land?",
        type: "toggle",
        key: "plotOwnership",
        options: ["Yes", "No"],
      },
      {
        id: "familyMembers",
        label: "Total family members",
        type: "number",
        key: "familyMembers",
        placeholder: "e.g. 4",
      },
      {
        id: "prevHouseScheme",
        label: "Availed any housing scheme before?",
        type: "toggle",
        key: "prevHouseScheme",
        options: ["Yes", "No"],
      },
      {
        id: "maritalStatus",
        label: "Marital status",
        type: "select",
        key: "maritalStatus",
        options: ["Select", "Single", "Married", "Widowed", "Divorced", "Separated"],
      },
    ],
  },
  {
    key: "employment",
    icon: "💼",
    title: "Employment & Skills",
    description: "Job training, skill schemes",
    fields: [
      {
        id: "employmentStatus",
        label: "Employment status",
        type: "select",
        key: "employmentStatus",
        options: ["Select", "Unemployed", "Part-time", "Salaried", "Self-employed", "Daily wage"],
      },
      {
        id: "lookingForJob",
        label: "Registered at employment office?",
        type: "toggle",
        key: "lookingForJob",
        options: ["Yes", "No"],
      },
      {
        id: "itiDone",
        label: "Completed ITI or vocational training?",
        type: "toggle",
        key: "itiDone",
        options: ["Yes", "No"],
      },
      {
        id: "skillDomain",
        label: "Skill area of interest",
        type: "select",
        key: "skillDomain",
        options: ["Select", "IT / Software", "Electrical", "Plumbing", "Construction", "Tailoring", "Beauty & Wellness", "Hospitality", "Other"],
      },
      {
        id: "educationLevel",
        label: "Education level",
        type: "select",
        key: "educationLevel",
        options: ["Select", "Below 10th", "10th pass", "Intermediate", "Diploma", "Graduate"],
      },
      {
        id: "bankAccount",
        label: "Has bank account?",
        type: "toggle",
        key: "bankAccount",
        options: ["Yes", "No"],
      },
    ],
  },
  {
    key: "women",
    icon: "👩",
    title: "Women & Maternity",
    description: "Widow, maternity, SHG support",
    fields: [
      {
        id: "maritalStatus",
        label: "Marital status",
        type: "select",
        key: "maritalStatus",
        options: ["Select", "Single", "Married", "Widowed", "Divorced", "Separated"],
      },
      {
        id: "pregnantLactating",
        label: "Pregnant or lactating?",
        type: "toggle",
        key: "pregnantLactating",
        options: ["Yes", "No"],
      },
      {
        id: "singleParent",
        label: "Single parent or widow-headed family?",
        type: "toggle",
        key: "singleParent",
        options: ["Yes", "No"],
      },
      {
        id: "numChildren",
        label: "Number of children",
        type: "number",
        key: "numChildren",
        placeholder: "e.g. 2",
      },
      {
        id: "shgMember",
        label: "SHG (self-help group) member?",
        type: "toggle",
        key: "shgMember",
        options: ["Yes", "No"],
      },
      {
        id: "familyMembers",
        label: "Total family members",
        type: "number",
        key: "familyMembers",
        placeholder: "e.g. 5",
      },
    ],
  },
  {
    key: "pension",
    icon: "🧓",
    title: "Senior Citizen & Pension",
    description: "Old age support, pensions",
    fields: [
      {
        id: "livingAlone",
        label: "Living alone with no family support?",
        type: "toggle",
        key: "livingAlone",
        options: ["Yes", "No"],
      },
      {
        id: "pensionStatus",
        label: "Currently receiving any pension?",
        type: "toggle",
        key: "pensionStatus",
        options: ["Yes", "No"],
      },
      {
        id: "maritalStatus",
        label: "Marital status",
        type: "select",
        key: "maritalStatus",
        options: ["Select", "Married", "Widowed", "Single", "Divorced"],
      },
      {
        id: "familySupport",
        label: "Family financial support available?",
        type: "toggle",
        key: "familySupport",
        options: ["Yes", "No"],
      },
      {
        id: "bankAccount",
        label: "Has bank account for DBT?",
        type: "toggle",
        key: "bankAccount",
        options: ["Yes", "No"],
      },
      {
        id: "aadharLinked",
        label: "Aadhaar linked to bank account?",
        type: "toggle",
        key: "aadharLinked",
        options: ["Yes", "No"],
      },
    ],
  },
  {
    key: "disability",
    icon: "♿",
    title: "Differently Abled",
    description: "Disability aid, certificates",
    fields: [
      {
        id: "disabilityType",
        label: "Type of disability",
        type: "select",
        key: "disabilityType",
        options: ["Select", "Visual", "Hearing", "Locomotor", "Intellectual", "Mental illness", "Multiple", "Other"],
      },
      {
        id: "disabilityPercent",
        label: "Disability percentage (%)",
        type: "number",
        key: "disabilityPercent",
        placeholder: "e.g. 40",
      },
      {
        id: "disabilityCert",
        label: "Has UDID disability certificate?",
        type: "toggle",
        key: "disabilityCert",
        options: ["Yes", "No"],
      },
      {
        id: "disabilitySchool",
        label: "Currently in school or college?",
        type: "toggle",
        key: "disabilitySchool",
        options: ["Yes", "No"],
      },
      {
        id: "disabilityEmployed",
        label: "Currently employed?",
        type: "toggle",
        key: "disabilityEmployed",
        options: ["Yes", "No"],
      },
      {
        id: "caregiver",
        label: "Has a family caregiver?",
        type: "toggle",
        key: "caregiver",
        options: ["Yes", "No"],
      },
    ],
  },
  {
    key: "health",
    icon: "🏥",
    title: "Health & Medical",
    description: "Aarogyasri, insurance",
    fields: [
      {
        id: "aarogyasri",
        label: "Has Aarogyasri or PMJAY card?",
        type: "toggle",
        key: "aarogyasri",
        options: ["Yes", "No"],
      },
      {
        id: "chronicDisease",
        label: "Has chronic illness?",
        type: "toggle",
        key: "chronicDisease",
        options: ["Yes", "No"],
      },
      {
        id: "diseaseType",
        label: "Type of condition",
        type: "select",
        key: "diseaseType",
        options: ["Select", "None", "Diabetes", "Hypertension", "Cancer", "Kidney disease", "Heart disease", "TB", "HIV/AIDS", "Other"],
      },
      {
        id: "familyMembers",
        label: "Total family members",
        type: "number",
        key: "familyMembers",
        placeholder: "e.g. 5",
      },
      {
        id: "pregnantInFamily",
        label: "Pregnant woman in family?",
        type: "toggle",
        key: "pregnantInFamily",
        options: ["Yes", "No"],
      },
      {
        id: "healthInsurance",
        label: "Has private health insurance?",
        type: "toggle",
        key: "healthInsurance",
        options: ["Yes", "No"],
      },
    ],
  },
  {
    key: "worker",
    icon: "🔧",
    title: "Unorganised Workers",
    description: "Labour card, weaver, fisher",
    fields: [
      {
        id: "workerType",
        label: "Type of work",
        type: "select",
        key: "workerType",
        options: ["Select", "Construction", "Weaving", "Fishing", "Domestic worker", "Beedi worker", "Auto/Taxi driver", "Street vendor", "Leather worker", "Other"],
      },
      {
        id: "labourCard",
        label: "Has labour card or e-Shram registered?",
        type: "toggle",
        key: "labourCard",
        options: ["Yes", "No"],
      },
      {
        id: "yearsInWork",
        label: "Years in this occupation",
        type: "number",
        key: "yearsInWork",
        placeholder: "e.g. 5",
      },
      {
        id: "workInjury",
        label: "Suffered work-related injury?",
        type: "toggle",
        key: "workInjury",
        options: ["Yes", "No"],
      },
      {
        id: "familyMembers",
        label: "Total family members",
        type: "number",
        key: "familyMembers",
        placeholder: "e.g. 4",
      },
      {
        id: "bankAccount",
        label: "Has bank account?",
        type: "toggle",
        key: "bankAccount",
        options: ["Yes", "No"],
      },
    ],
  },
];